/** Rebuild with @oai/artifact-tool. See ../README.md for the runtime setup. */
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {createRequire} from 'node:module';

const require=createRequire(import.meta.url);
const artifactPath=require.resolve('@oai/artifact-tool');
const {Presentation,PresentationFile}=await import(pathToFileURL(artifactPath));
const {FontLibrary}=await import(pathToFileURL(path.resolve(path.dirname(artifactPath),'../node_modules/skia-canvas/lib/index.js')));
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const out=process.env.BUILD_DIR||'/private/tmp/mapexport-deck/build';
await fs.mkdir(out,{recursive:true});
const fontdir=path.join(root,'references/MapExport Design System/fonts');
for(const [file,family] of [['Mayonnaise_Black','Mayonnaise Black'],['Apfel_Grotezk_Regular','Apfel Grotezk'],['Apfel_Grotezk_Fett','Apfel Grotezk']])FontLibrary.use(family,path.join(fontdir,file+'.ttf'));
const p=Presentation.create({slideSize:{width:1280,height:720}});
const C={cream:'#FEF9E4',orange:'#F4501E',ink:'#18180F',mint:'#7ECAB6',line:'#D9D0AE'};
const assets=path.join(root,'presentations/assets');
const source='Sources: live https://coen.at/mapexport/ inspected and exported 13 September 2026; repository README.md, script.js and references/How to draw a good street map.md. Map data © OpenStreetMap contributors (ODbL), https://www.openstreetmap.org/copyright .';
const slides=[];
function text(s,str,x,y,w,h,size=28,color=C.ink,font='Apfel Grotezk',bold=false){const t=s.shapes.add({geometry:'textbox',position:{left:x,top:y,width:w,height:h},fill:'none',line:{fill:'none',width:0}});t.text=str;t.text.style={typeface:font,fontSize:size,color,bold,autoFit:'none'};return t;}
function box(s,x,y,w,h,fill){return s.shapes.add({geometry:'rect',position:{left:x,top:y,width:w,height:h},fill,line:{fill:'none',width:0}});}
async function img(s,file,x,y,w,h,fit='cover'){s.images.add({blob:await fs.readFile(path.join(assets,file)),contentType:'image/png',alt:file.replaceAll('-',' '),fit,position:{left:x,top:y,width:w,height:h}});}
function base(title,kicker='WORKSHOP',bg=C.cream){const s=p.slides.add();s.background.fill=bg;const n=p.slides.items.length;slides.push({title});text(s,kicker,48,25,1136,30,17,bg===C.orange?C.cream:C.orange,'Apfel Grotezk',true);text(s,title,48,67,1180,112,55,bg===C.orange?C.cream:C.ink,'Mayonnaise Black');text(s,'MAPEXPORT  /  USE-IT     ·     Map data © OpenStreetMap contributors',48,675,1050,25,15,bg===C.orange?C.cream:C.ink);text(s,String(n).padStart(2,'0'),1170,675,62,25,15,bg===C.orange?C.cream:C.ink);return s;}
function notes(s,content){s.speakerNotes.textFrame.setText(content+'\n\n'+source);}
function row(s,num,title,body,y,w=1080){text(s,num,48,y,72,58,40,C.orange,'Mayonnaise Black');text(s,title,132,y,w-84,42,30,C.ink,'Apfel Grotezk',true);text(s,body,132,y+46,w-84,67,26);}
// 01 — bold product cover with authentic map crop.
{const s=p.slides.add();s.background.fill=C.orange;slides.push({title:'MapExport'});await img(s,'ghent-map.png',700,0,580,720);text(s,'USE-IT DESIGN WORKSHOP',48,40,650,40,21,C.cream,'Apfel Grotezk',true);text(s,'MAP\nEXPORT',40,135,680,290,124,C.cream,'Mayonnaise Black');text(s,'Your city.\nAn editable map.',48,455,615,125,43,C.cream);text(s,'coen.at/mapexport',48,635,600,40,24,C.cream);box(s,700,686,580,34,C.cream);text(s,'Map data © OpenStreetMap contributors',718,688,550,29,15);notes(s,'Welcome. Today we will turn a city area into an editable SVG, explore its layers, then export our own cities. Suggested flow: 10 minutes introduction, 5 minutes live demo, 20 minutes hands-on and 10 minutes discussion. Timings are adjustable. The map shown is the live Gent export included with this deck.');}
// 02
{const s=base('LESS REPETITION. MORE LOCAL CHARACTER.','THE PROBLEM');text(s,'Before you can tell the story\nof a city, you need a base map.',48,199,600,115,38);row(s,'01','Trace streets and blocks','Build a clear street hierarchy.',340,650);row(s,'02','Place and check names','Keep labels readable and editable.',485,650);box(s,804,190,428,442,C.mint);text(s,'What if the\nfirst draft\nwas already\nthere?',833,243,370,300,52,C.ink,'Mayonnaise Black');notes(s,'Ask for a quick show of hands: who has traced a base map manually? MapExport tackles repetitive groundwork: streets, blocks and street labels. Do not promise a measured time saving. The amount of cleanup depends on the city and the source data.');}
// 03
{const s=base('A BASE MAP YOU CAN MAKE YOUR OWN','THE RESULT');await img(s,'ghent-map.png',48,194,768,446);text(s,'Editable SVG',855,207,375,50,36,C.orange,'Apfel Grotezk',true);text(s,'Separate layers and groups\n\nVector shapes and street labels\n\nA starting point for your\nUSE-IT visual language',855,276,374,296,28);text(s,'Gent / live export',855,599,375,30,19);notes(s,'Point out water, roads, parks and blocks. SVG is a vector file: it can be scaled and edited in a vector editor. This is a base map, not a complete travel guide. Sample: presentations/assets/ghent-demo.svg.');}
// 04
{const s=base('FROM OPEN DATA TO YOUR DESIGN','HOW IT WORKS');const items=[['Choose an area','Find your city and draw a rectangle.'],['Get the map features','MapExport retrieves OpenStreetMap data.'],['Build the base map','It draws roads, derives blocks and places labels.'],['Continue in your editor','Download an SVG and open it in Illustrator or Inkscape.']];items.forEach((a,i)=>row(s,String(i+1).padStart(2,'0'),a[0],a[1],184+i*112));notes(s,'OpenStreetMap provides geographical data. MapExport transforms those features into a designed SVG, including computed city blocks and road labels. City blocks are areas between roads, not individual building footprints. Data coverage and quality vary by location.');}
// 05
{const s=base('MEET YOUR WORKSPACE','IN THE BROWSER');await img(s,'live-area.png',48,177,946,473,'contain');text(s,'1  Find a city',1020,209,228,70,25,C.orange,'Apfel Grotezk',true);text(s,'2  Draw an area',1020,332,230,75,25,C.orange,'Apfel Grotezk',true);text(s,'3  Choose layers',1020,456,230,75,25,C.orange,'Apfel Grotezk',true);notes(s,'Open https://coen.at/mapexport/ . The controls are on the left, the map on the right. Search, pick the matching location and use Draw rectangle. Screenshot captured from the live site, 13 September 2026. Live controls may evolve.');}
// 06
{const s=base('START WITH A WALKABLE CITY CENTRE','CHOOSE YOUR AREA');await img(s,'live-options.png',48,188,828,466,'contain');text(s,'Keep the first area small.',904,208,323,98,34,C.orange,'Apfel Grotezk',true);text(s,'Include a recognisable landmark.\n\nCheck the area and printed size.\n\nLeave room for your eventual layout.',904,332,326,289,27);notes(s,'For the first exercise choose a manageable central neighbourhood, not an entire metropolitan area. In the sample the rectangle is roughly 2.3 × 2.9 km. The live interface shows approximate printed dimensions. Avoid implying that the website has an A3 selector. A larger export has more objects and may take longer.');}
// 07
{const s=base('CHOOSE WHAT YOUR MAP NEEDS','LAYERS');await img(s,'ghent-map.png',662,183,570,467);text(s,'The essentials',48,193,570,50,34,C.orange,'Apfel Grotezk',true);text(s,'Roads and city blocks\nWater and green space\nStreet names',48,257,559,160,32);text(s,'Add detail with purpose',48,445,579,50,32,C.orange,'Apfel Grotezk',true);text(s,'For example: transit or pedestrian routes.\nKeep only what helps your reader.',48,504,570,100,27);notes(s,'Show the layer checkboxes on the live site. Available options include water bodies, waterways, city blocks, parks/green space, roads, railways and transit features. Street-name controls include road categories. Explain that all available detail does not necessarily improve a printed USE-IT map. City blocks do not represent each individual building.');}
// 08
{const s=base('EXPORT FOR YOUR EDITOR','DOWNLOAD');const x=[48,678];['ILLUSTRATOR','INKSCAPE'].forEach((a,i)=>{text(s,a,x[i],206,560,75,46,C.orange,'Mayonnaise Black');text(s,i===0?'Choose “SVG (Illustrator)”':'Choose “SVG (Inkscape / others)”',x[i],305,554,95,30,C.ink,'Apfel Grotezk',true);text(s,'Export SVG → Download\nThen use File → Open.',x[i],427,544,110,32);});box(s,639,206,2,346,C.line);text(s,'Keep the original export. Save your edits as a separate file.',48,598,1182,44,27);notes(s,'These are the option labels observed on the live site. Use File > Open, rather than placing the SVG as a linked image in another document. Inspect Layers or Layers and Objects after opening; group/layer presentation differs between editors. Keep the original SVG for recovery.');}
// 09
{const s=base('FIND THE LAYER. EDIT THE RIGHT THINGS.','INSIDE THE SVG');text(s,'Map content',62,210,590,58,38,C.orange,'Apfel Grotezk',true);['City blocks','Parks & green space','Roads','Street names'].forEach((v,i)=>{box(s,74,292+i*68,6,40,i===0?C.orange:C.mint);text(s,v,110,290+i*68,510,48,30);});text(s,'Open the Layers panel.',715,221,488,58,32,C.orange,'Apfel Grotezk',true);text(s,'Expand Map content.\n\nToggle a layer to see what it contains.\n\nKeep groups intact while you explore.',715,312,486,290,30);notes(s,'This is a simplified layer list, not a screenshot of an editor. The actual Gent SVG has a Background layer and a clipped Map content parent. Expand Map content to find City blocks. Exact grouping can differ by export version and editor. Keep the crop/clipping group intact: ungrouping everything can expose geometry outside the selected area.');}
// 10
{const s=base('LIVE DEMO: CHANGE ALL THE BLOCKS','INKSCAPE / ABOUT 5 MINUTES',C.mint);await img(s,'ghent-map.png',48,190,432,350);await img(s,'ghent-recoloured.png',492,190,432,350);text(s,'BEFORE',48,551,420,34,20,C.ink,'Apfel Grotezk',true);text(s,'ONE COLOUR CHANGE',492,551,442,34,20,C.ink,'Apfel Grotezk',true);text(s,'1  Open the SVG\n\n2  Find City blocks\n\n3  Select its blocks\n\n4  Change the fill',960,201,278,352,25,C.ink,'Apfel Grotezk',true);text(s,'581 blocks in this example. Roads, water and parks keep their colours.',48,605,1190,45,26);notes(s,'DEMO SCRIPT\nOpen presentations/assets/ghent-demo.svg in Inkscape. Fit the page to the window (5). Open Layer > Layers and Objects and expand Map content. Find City blocks. Enter that layer and select its child paths, or select one block and use Edit > Select Same > Fill Color. Verify that only the city-block paths are selected: this sample contains 581. Lock unrelated layers first if their objects share the same fill. Click a palette colour or use Object > Fill and Stroke to change Fill (do not Shift-click, which changes Stroke). Water, roads and parks should retain their colours. Undo once to show that all blocks changed together. Save a separate edited SVG.\nThe preview on the right changes every child path in city_blocks to #F2CA76 and nothing else. It was rendered by Inkscape from the actual export. This slide is a prompt to switch to a live editor, not a recording of UI clicks. Backup: ghent-recoloured.svg.\nInkscape Select Same documentation: https://inkscape.org/en/doc/tutorials/basic/tutorial-basic.pt_BR.html/ .');}
// 11
{const s=base('YOU BRING THE LOCAL KNOWLEDGE','FROM BASE MAP TO USE-IT MAP');text(s,'MapExport supplies\nthe groundwork.',48,209,559,145,48,C.orange,'Mayonnaise Black');text(s,'You decide what\nmatters to visitors.',48,403,575,145,48,C.ink,'Mayonnaise Black');text(s,'Choose and position your local tips.\n\nAdd illustrations, symbols and character.\n\nCheck names and the street hierarchy.\n\nProof the map at its final printed size.',701,215,537,374,29);text(s,'Keep OpenStreetMap attribution in the finished map.',701,606,525,48,21,C.orange);notes(s,'The tool does not choose the local tips, judge every label or make the final page composition. Designers still simplify, edit and proof. Before publication, check that the map is readable at the intended size, including labels and contrast. The SVG contains OSM attribution metadata, but that is not a substitute for visible attribution in the finished publication. Attribution guidance: https://www.openstreetmap.org/copyright .');}
// 12
{const s=base('YOUR CITY. YOUR TURN.','HANDS-ON / SUGGESTED 20 MINUTES',C.orange);text(s,'Export a small area.\nOpen it in your editor.\nMake one change.',48,201,1168,315,75,C.cream,'Mayonnaise Black');text(s,'coen.at/mapexport',48,584,1173,65,37,C.cream);notes(s,'Invite participants to work individually or in pairs. Allow about 20 minutes, adjusting for the group. Everyone should have Illustrator or Inkscape available. Have ghent-demo.svg ready for anyone whose export is delayed so they can still practise editing.');}
// 13
{const s=base('YOUR FIRST EXPORT','HANDS-ON / PART 1');row(s,'01','Find your city','Draw a rectangle around a familiar central area.',185);row(s,'02','Choose your layers and SVG format','Pick the format that matches your editor.',303);row(s,'03','Export, download and open','Use File → Open in Illustrator or Inkscape.',421);text(s,'Success: you can see your city and inspect its layers or groups.',48,596,1180,54,28,C.orange,'Apfel Grotezk',true);notes(s,'Walk around and help participants with the boundary, format choice and opening the file. Ask them to keep the original download. A successful first export matters more than choosing the perfect final map extent.');}
// 14
{const s=base('MAKE THE FILE YOURS','HANDS-ON / PART 2');row(s,'01','Change all city blocks to a new colour','Select the block paths together. Keep roads and water unchanged.',185);row(s,'02','Explore the structure','Hide one layer, restore it, then find a street label.',303);row(s,'03','Save a working copy','Keep one observation to share with the group.',421);text(s,'Done early? Compare the result with a place you know well.',48,596,1180,54,28,C.orange,'Apfel Grotezk',true);notes(s,'Participants can use either editor. Inkscape: use the demo workflow. Illustrator: expand the relevant group in Layers, select its child block paths and change Fill; Select > Same > Fill Color can help if only the intended objects use that colour. Check the selection before recolouring. Ask participants to note one concrete issue or useful feature for discussion.');}
// 15
{const s=base('KEEP MOVING IF SOMETHING GETS STUCK','WORKSHOP HELP');row(s,'01','Export taking a while?','Watch the progress message. Try a smaller area for the next export.',185);row(s,'02','Need a file to practise with?','Use the included Gent SVG while your own export finishes.',303);row(s,'03','File looks unexpected in your editor?','Check the SVG format, fonts and layer visibility.',421);text(s,'A useful bug report: city + selected area + editor + what you expected.',48,596,1180,54,27,C.orange,'Apfel Grotezk',true);notes(s,'MapExport relies on public map-data services, which can be slow or temporarily unavailable. Do not have everyone repeatedly click export at once. For workshop continuity, use presentations/assets/ghent-demo.svg. If text looks different, inspect any missing-font warning and compare with the browser preview. Record precise reproduction steps and, where useful, a screenshot.');}
// 16
{const s=base('WHAT SHOULD MAPEXPORT DO BETTER?','OPEN DISCUSSION',C.mint);text(s,'What saved you work?\n\nWhat was confusing?\n\nWhat is missing for your city?',48,205,775,360,43,C.ink,'Mayonnaise Black');box(s,880,202,352,370,C.cream);text(s,'SHOW ONE\nEXAMPLE.',907,235,295,148,52,C.orange,'Mayonnaise Black');text(s,'Then tell us the one\nchange that would\nhelp you most.',907,425,284,119,27);text(s,'Collect: observation → impact on your workflow → suggested improvement',48,610,1190,40,25);notes(s,'End here and invite an open discussion. Collect feedback in three columns on a board or shared document: observation, impact and desired change. Capture the city, area and editor for reproducible problems. Ask for concrete examples and let other participants add their experience before prioritising. Distinguish bugs, usability issues and feature wishes. Finish by asking each person for the one improvement that matters most; do not promise delivery dates.');}
await fs.writeFile(path.join(out,'slide-titles.json'),JSON.stringify(slides,null,2));
await (await PresentationFile.exportPptx(p)).save(path.join(out,'candidate.pptx'));
for(let i=0;i<p.slides.items.length;i++){const b=await p.export({slide:p.slides.items[i],format:'png',scale:1});await fs.writeFile(path.join(out,`slide-${String(i+1).padStart(2,'0')}.png`),new Uint8Array(await b.arrayBuffer()));}
console.log(`Built ${p.slides.items.length} slides in ${out}`);
